name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      version: 42

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install winget - Windows
        uses: Cyberboss/install-winget@v1
      - name: Install Software
        run: |
          winget install --disable-interactivity --accept-source-agreements --accept-package-agreements 7zip.7zip
      - name: Extract and Recompress
        run: |
          7z x ngspice-42_64.7z
          7z a ngspice-42_64.zip .\Spice64\
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ngspice-42_64.zip
          body: First zip package for ngspice 42
  
